import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import api from '../api';
export default function Restaurant(){ const { id } = useParams(); const [rest,setRest]=useState(null); const [menu,setMenu]=useState([]); const [cart,setCart]=useState([]);
  useEffect(()=>{ api.get('/restaurants').then(r=>{ const found = r.data.find(x=>String(x.id)===String(id)); setRest(found||r.data[0]); }).catch(()=>{}); setMenu([{id:1,name:'Aloo Paratha',price:60},{id:2,name:'Paneer Curry',price:140}]); },[id]);
  function addToCart(it){ setCart(prev=>[...prev, {...it, qty:1}]); }
  async function placeOrder(){ const token = 'demo-token-123'; if(!token) return alert('Please login first'); const items_json = cart.map(i=>({id:i.id,name:i.name,qty:i.qty,price:i.price})); const total = cart.reduce((s,it)=>s + it.price*it.qty,0); try{ const res = await api.post('/orders',{ customer_id:1, restaurant_id:rest.id, items_json, total_amount: total }); alert('Order placed: #' + res.data.id); setCart([]); }catch(err){ alert('Order failed'); } }
  return (<div className='container'>{rest ? (<div><div className='card'><img src={rest.image} style={{width:'100%',height:260,objectFit:'cover'}} /><div style={{padding:12}}><h2>{rest.name}</h2><div className='muted'>{rest.cuisine} • {rest.eta}</div></div></div><div style={{display:'flex',gap:16,marginTop:12}}><div style={{flex:1}}><div className='card'><h3>Menu</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}>{menu.map(it=>(<div key={it.id} className='card' style={{display:'flex',gap:12,alignItems:'center'}}><div style={{flex:1}}><div style={{fontWeight:700}}>{it.name}</div><div className='muted'>₹{it.price}</div></div><div style={{marginLeft:'auto'}}><button className='btn' onClick={()=>addToCart(it)}>Add</button></div></div>))}</div></div></div><aside style={{width:340}} className='card'><h4>Your cart</h4>{cart.length===0 ? <div className='muted'>No items</div> : cart.map((c,i)=>(<div key={i} style={{display:'flex',justifyContent:'space-between',marginTop:8}}><div>{c.name} x{c.qty}</div><div>₹{c.price*c.qty}</div></div>))}<div style={{marginTop:12}}><strong>Total: ₹{cart.reduce((s,it)=>s + it.price*it.qty,0)}</strong></div><div style={{marginTop:12}}><button className='btn' onClick={placeOrder} style={{width:'100%'}}>Place Order</button></div></aside></div></div>): <div className='muted'>Loading...</div>}</div>);
}
